export const defaults=nameList=>[
  {
    key:'--maxWidth',
    label:nameList['--maxWidth'],
    value:'100%',
    type:'text',
  },
  {
    key:'--menuWidth',
    label:nameList['--menuWidth'],
    value:'180px',
    type:'text',
  },
  {
    key:'--collapseWidth',
    label:nameList['--collapseWidth'],
    value:'50px',
    type:'text',
  },
  {
    key:'--collapseMenuWidth',
    label:nameList['--collapseMenuWidth'],
    value:'160px',
    type:'text',
  },
  {
    key:'--headerHeight',
    label:nameList['--headerHeight'],
    value:'58px',
    type:'text',
  },
  {
    key:'--footerHeight',
    label:nameList['--footerHeight'],
    value:'40px',
    type:'text',
  },
  {
    key:'--breadHeight',
    label:nameList['--breadHeight'],
    value:'40px',
    type:'text',
  },
  {
    key:'--topbarHeight',
    label:nameList['--topbarHeight'],
    value:'0px',
    type:'text',
  },

  {
    key:'--bannerBgColor',
    label:nameList['--bannerBgColor'],
    value:'#21364a',
    type:'color',
  },
  {
    key:'--navBgColor',
    label:nameList['--navBgColor'],
    value:'#21364a',
    type:'color',
  },
  {
    key:'--menuBgColor',
    label:nameList['--menuBgColor'],
    value:'#2d4054',
    type:'color',
  },
  /* {
    key:'--deepMenuBgColor',
    label:nameList['--deepMenuBgColor'],
    value:'hsla(0,0%,0%,.03)',
    type:'color',
  }, */
  {
    key:'--appBgColor',
    label:nameList['--appBgColor'],
    value:'#eaeff2',
    type:'color',
  },
  {
    key:'--pageBgColor',
    label:nameList['--pageBgColor'],
    value:'#eaeff2',
    type:'color',
  },
  {
    key:'--footerBgColor',
    label:nameList['--footerBgColor'],
    value:'#ffffff',
    type:'color',
  },
  {
    key:'--appColor',
    label:nameList['--appColor'],
    value:'#ffffff',
    type:'color',
  },
  {
    key:'--linkColor',
    label:nameList['--linkColor'],
    value:'#f0f0f0',
    type:'color',
  },
  {
    key:'--linkHoverColor',
    label:nameList['--linkHoverColor'],
    value:'#40a9ff',
    type:'color',
  },
  {
    key:'--linkActiveColor',
    label:nameList['--linkActiveColor'],
    value:'#40a9ff',
    type:'color',
  },
];
export const theme1=nameList=>[
  {
    key:'--maxWidth',
    label:nameList['--maxWidth'],
    value:'100%',
    type:'text',
  },
  {
    key:'--menuWidth',
    label:nameList['--menuWidth'],
    value:'200px',
    type:'text',
  },
  {
    key:'--collapseWidth',
    label:nameList['--collapseWidth'],
    value:'50px',
    type:'text',
  },
  {
    key:'--collapseMenuWidth',
    label:nameList['--collapseMenuWidth'],
    value:'160px',
    type:'text',
  },
  {
    key:'--headerHeight',
    label:nameList['--headerHeight'],
    value:'52px',
    type:'text',
  },
  {
    key:'--footerHeight',
    label:nameList['--footerHeight'],
    value:'40px',
    type:'text',
  },
  {
    key:'--breadHeight',
    label:nameList['--breadHeight'],
    value:'40px',
    type:'text',
  },
  {
    key:'--topbarHeight',
    label:nameList['--topbarHeight'],
    value:'0px',
    type:'text',
  },

  {
    key:'--bannerBgColor',
    label:nameList['--bannerBgColor'],
    value:'#212121',
    type:'color',
  },
  {
    key:'--navBgColor',
    label:nameList['--navBgColor'],
    value:'#212121',
    type:'color',
  },
  {
    key:'--menuBgColor',
    label:nameList['--menuBgColor'],
    value:'#212121',
    type:'color',
  },
  /* {
    key:'--deepMenuBgColor',
    label:nameList['--deepMenuBgColor'],
    value:'hsla(0,0%,0%,.03)',
    type:'color',
  }, */
  {
    key:'--appBgColor',
    label:nameList['--appBgColor'],
    value:'#121212',
    type:'color',
  },
  {
    key:'--pageBgColor',
    label:nameList['--pageBgColor'],
    value:'#121212',
    type:'color',
  },
  {
    key:'--footerBgColor',
    label:nameList['--footerBgColor'],
    value:'#121212',
    type:'color',
  },
  {
    key:'--appColor',
    label:nameList['--appColor'],
    value:'rgba(255,255,255,.87)',
    type:'color',
  },
  {
    key:'--linkColor',
    label:nameList['--linkColor'],
    value:'#40a9ff',
    type:'color',
  },
  {
    key:'--linkHoverColor',
    label:nameList['--linkHoverColor'],
    value:'#00a8cc',
    type:'color',
  },
  {
    key:'--linkActiveColor',
    label:nameList['--linkActiveColor'],
    value:'#00a8cc',
    type:'color',
  },
];
export const dark=nameList=>[
  {
    key:'--maxWidth',
    label:nameList['--maxWidth'],
    value:'100%',
    type:'text',
  },
  {
    key:'--menuWidth',
    label:nameList['--menuWidth'],
    value:'200px',
    type:'text',
  },
  {
    key:'--collapseWidth',
    label:nameList['--collapseWidth'],
    value:'50px',
    type:'text',
  },
  {
    key:'--collapseMenuWidth',
    label:nameList['--collapseMenuWidth'],
    value:'160px',
    type:'text',
  },
  {
    key:'--headerHeight',
    label:nameList['--headerHeight'],
    value:'52px',
    type:'text',
  },
  {
    key:'--footerHeight',
    label:nameList['--footerHeight'],
    value:'40px',
    type:'text',
  },
  {
    key:'--breadHeight',
    label:nameList['--breadHeight'],
    value:'40px',
    type:'text',
  },
  {
    key:'--topbarHeight',
    label:nameList['--topbarHeight'],
    value:'0px',
    type:'text',
  },

  {
    key:'--bannerBgColor',
    label:nameList['--bannerBgColor'],
    value:'#212121',
    type:'color',
  },
  {
    key:'--navBgColor',
    label:nameList['--navBgColor'],
    value:'#212121',
    type:'color',
  },
  {
    key:'--menuBgColor',
    label:nameList['--menuBgColor'],
    value:'#212121',
    type:'color',
  },
  /* {
    key:'--deepMenuBgColor',
    label:nameList['--deepMenuBgColor'],
    value:'hsla(0,0%,0%,.03)',
    type:'color',
  }, */
  {
    key:'--appBgColor',
    label:nameList['--appBgColor'],
    value:'#121212',
    type:'color',
  },
  {
    key:'--pageBgColor',
    label:nameList['--pageBgColor'],
    value:'#121212',
    type:'color',
  },
  {
    key:'--footerBgColor',
    label:nameList['--footerBgColor'],
    value:'#121212',
    type:'color',
  },
  {
    key:'--appColor',
    label:nameList['--appColor'],
    value:'rgba(255,255,255,.87)',
    type:'color',
  },
  {
    key:'--linkColor',
    label:nameList['--linkColor'],
    value:'#40a9ff',
    type:'color',
  },
  {
    key:'--linkHoverColor',
    label:nameList['--linkHoverColor'],
    value:'#00a8cc',
    type:'color',
  },
  {
    key:'--linkActiveColor',
    label:nameList['--linkActiveColor'],
    value:'#00a8cc',
    type:'color',
  },
];
export const light=nameList=>[
  {
    key:'--maxWidth',
    label:nameList['--maxWidth'],
    value:'100%',
    type:'text',
  },
  {
    key:'--menuWidth',
    label:nameList['--menuWidth'],
    value:'200px',
    type:'text',
  },
  {
    key:'--collapseWidth',
    label:nameList['--collapseWidth'],
    value:'50px',
    type:'text',
  },
  {
    key:'--collapseMenuWidth',
    label:nameList['--collapseMenuWidth'],
    value:'160px',
    type:'text',
  },
  {
    key:'--headerHeight',
    label:nameList['--headerHeight'],
    value:'52px',
    type:'text',
  },
  {
    key:'--footerHeight',
    label:nameList['--footerHeight'],
    value:'40px',
    type:'text',
  },
  {
    key:'--breadHeight',
    label:nameList['--breadHeight'],
    value:'40px',
    type:'text',
  },
  {
    key:'--topbarHeight',
    label:nameList['--topbarHeight'],
    value:'0px',
    type:'text',
  },

  {
    key:'--bannerBgColor',
    label:nameList['--bannerBgColor'],
    value:'#fcfcfc',
    type:'color',
  },
  {
    key:'--navBgColor',
    label:nameList['--navBgColor'],
    value:'#fcfcfc',
    type:'color',
  },
  {
    key:'--menuBgColor',
    label:nameList['--menuBgColor'],
    value:'#fcfcfc',
    type:'color',
  },
  /* {
    key:'--deepMenuBgColor',
    label:nameList['--deepMenuBgColor'],
    value:'hsla(0,0%,0%,.03)',
    type:'color',
  }, */
  {
    key:'--appBgColor',
    label:nameList['--appBgColor'],
    value:'#f3f3f3',
    type:'color',
  },
  {
    key:'--pageBgColor',
    label:nameList['--pageBgColor'],
    value:'#f3f3f3',
    type:'color',
  },
  {
    key:'--footerBgColor',
    label:nameList['--footerBgColor'],
    value:'#ffffff',
    type:'color',
  },
  {
    key:'--appColor',
    label:nameList['--appColor'],
    value:'#333333',
    type:'color',
  },
  {
    key:'--linkColor',
    label:nameList['--linkColor'],
    value:'#444444',
    type:'color',
  },
  {
    key:'--linkHoverColor',
    label:nameList['--linkHoverColor'],
    value:'#40a9ff',
    type:'color',
  },
  {
    key:'--linkActiveColor',
    label:nameList['--linkActiveColor'],
    value:'#40a9ff',
    type:'color',
  },
];
export const portal=nameList=>[
  {
    key:'--maxWidth',
    label:nameList['--maxWidth'],
    value:'1200px',
    type:'text',
  },
  {
    key:'--menuWidth',
    label:nameList['--menuWidth'],
    value:'200px',
    type:'text',
  },
  {
    key:'--collapseWidth',
    label:nameList['--collapseWidth'],
    value:'50px',
    type:'text',
  },
  {
    key:'--collapseMenuWidth',
    label:nameList['--collapseMenuWidth'],
    value:'160px',
    type:'text',
  },
  {
    key:'--headerHeight',
    label:nameList['--headerHeight'],
    value:'52px',
    type:'text',
  },
  {
    key:'--footerHeight',
    label:nameList['--footerHeight'],
    value:'40px',
    type:'text',
  },
  {
    key:'--breadHeight',
    label:nameList['--breadHeight'],
    value:'40px',
    type:'text',
  },
  {
    key:'--topbarHeight',
    label:nameList['--topbarHeight'],
    value:'0px',
    type:'text',
  },

  {
    key:'--bannerBgColor',
    label:nameList['--bannerBgColor'],
    value:'#21364a',
    type:'color',
  },
  {
    key:'--navBgColor',
    label:nameList['--navBgColor'],
    value:'#21364a',
    type:'color',
  },
  {
    key:'--menuBgColor',
    label:nameList['--menuBgColor'],
    value:'#2d4054',
    type:'color',
  },
  /* {
    key:'--deepMenuBgColor',
    label:nameList['--deepMenuBgColor'],
    value:'hsla(0,0%,0%,.03)',
    type:'color',
  }, */
  {
    key:'--appBgColor',
    label:nameList['--appBgColor'],
    value:'#eaeff2',
    type:'color',
  },
  {
    key:'--pageBgColor',
    label:nameList['--pageBgColor'],
    value:'#eaeff2',
    type:'color',
  },
  {
    key:'--footerBgColor',
    label:nameList['--footerBgColor'],
    value:'#ffffff',
    type:'color',
  },
  {
    key:'--appColor',
    label:nameList['--appColor'],
    value:'#ffffff',
    type:'color',
  },
  {
    key:'--linkColor',
    label:nameList['--linkColor'],
    value:'#f0f0f0',
    type:'color',
  },
  {
    key:'--linkHoverColor',
    label:nameList['--linkHoverColor'],
    value:'#40a9ff',
    type:'color',
  },
  {
    key:'--linkActiveColor',
    label:nameList['--linkActiveColor'],
    value:'#40a9ff',
    type:'color',
  },
];
export const skeleton=nameList=>[
  {
    key:'--maxWidth',
    label:nameList['--maxWidth'],
    value:'100%',
    type:'text',
  },
  {
    key:'--menuWidth',
    label:nameList['--menuWidth'],
    value:'200px',
    type:'text',
  },
  {
    key:'--collapseWidth',
    label:nameList['--collapseWidth'],
    value:'50px',
    type:'text',
  },
  {
    key:'--collapseMenuWidth',
    label:nameList['--collapseMenuWidth'],
    value:'160px',
    type:'text',
  },
  {
    key:'--headerHeight',
    label:nameList['--headerHeight'],
    value:'52px',
    type:'text',
  },
  {
    key:'--footerHeight',
    label:nameList['--footerHeight'],
    value:'40px',
    type:'text',
  },
  {
    key:'--breadHeight',
    label:nameList['--breadHeight'],
    value:'40px',
    type:'text',
  },
  {
    key:'--topbarHeight',
    label:nameList['--topbarHeight'],
    value:'0px',
    type:'text',
  },

  {
    key:'--bannerBgColor',
    label:nameList['--bannerBgColor'],
    value:'hsla(0,0%,0%,.2)',
    type:'color',
  },
  {
    key:'--navBgColor',
    label:nameList['--navBgColor'],
    value:'hsla(0,0%,0%,.1)',
    type:'color',
  },
  {
    key:'--menuBgColor',
    label:nameList['--menuBgColor'],
    value:'hsla(0,0%,0%,.18)',
    type:'color',
  },
  /* {
    key:'--deepMenuBgColor',
    label:nameList['--deepMenuBgColor'],
    value:'hsla(0,0%,0%,.015)',
    type:'color',
  }, */
  {
    key:'--appBgColor',
    label:nameList['--appBgColor'],
    value:'hsla(0,0%,0%,.08)',
    type:'color',
  },
  {
    key:'--pageBgColor',
    label:nameList['--pageBgColor'],
    value:'hsla(0,0%,0%,.08)',
    type:'color',
  },
  {
    key:'--footerBgColor',
    label:nameList['--footerBgColor'],
    value:'hsla(0,0%,0%,.15)',
    type:'color',
  },
  {
    key:'--appColor',
    label:nameList['--appColor'],
    value:'#f0f0f0',
    type:'color',
  },
  {
    key:'--linkColor',
    label:nameList['--linkColor'],
    value:'#f0f0f0',
    type:'color',
  },
  {
    key:'--linkHoverColor',
    label:nameList['--linkHoverColor'],
    value:'#40a9ff',
    type:'color',
  },
  {
    key:'--linkActiveColor',
    label:nameList['--linkActiveColor'],
    value:'#40a9ff',
    type:'color',
  },
];

const themeList=nameList=>[
  {
    name:'defaults',//nameList['defaults'],
    key:'defaults',
    list:defaults(nameList),
    type:'theme',
  },
  {
    name:nameList['theme1'],
    key:'theme1',
    list:theme1(nameList),
    type:'theme',
  },
  {
    name:nameList['dark'],
    key:'dark',
    list:dark(nameList),
    type:'theme',
  },
  {
    name:nameList['light'],
    key:'light',
    list:light(nameList),
    type:'theme',
  },
  {
    name:nameList['portal'],
    key:'portal',
    list:portal(nameList),
    type:'theme',
  },
  {
    name:nameList['skeleton'],
    key:'skeleton',
    list:skeleton(nameList),
    type:'theme',
  },
];

export default themeList;

